;#############################################################################
;#
;#                          PUBLIC DOMAIN NOTICE                         
;#                Mark O. Hatfield Clinical Research Center
;#                      National Institues of Health
;#           United States Department of Health and Human Services
;#                                                                         
;#  This software is a United States Government Work under the terms of the
;#  United States Copyright Act. It was written as part of the authors'
;#  official duties as United States Government employees and contractors
;#  and thus cannot be copyrighted. This software is freely available
;#  to the public for use. The National Institutes of Health Clinical Center
;#  and the #  United States Government have not placed any restriction on
;#  its use or reproduction.
;#                                                                        
;#  Although all reasonable efforts have been taken to ensure the accuracy 
;#  and reliability of the software and data, the National Institutes of
;#  Health Clinical Center and the United States Government do not and cannot
;#  warrant the performance or results that may be obtained by using this 
;#  software or data. The National Institutes of Health Clinical Center and
;#  the U.S. Government disclaim all warranties, expressed or implied,
;#  including warranties of performance, merchantability or fitness for any
;#  particular purpose.
;#                                                                         
;#  For full details, please see the licensing guidelines in the LICENSE file.
;#
;#############################################################################

[Predictions]
FileMap = demo_data/visualization_file_map
DefaultHighlightThreshold = 0.5
DefaultNumBlanks = 0
DefaultMinProbability = 0.5

[Ranking]
DefaultGoldScorer = CountSegmentsAndTokens
DefaultModelScorer = CountSegmentsAndTokens
CountSegmentsAndTokens Score Description = # Segments/# Tokens
SumTokenScores Score Description = Total Token Score
DensityScorer Score Description = Mean Token Score

[Classification]
Method = Binning
; Format: <Class_1>:<Threshold_1>,<Class_2>:<Threshold_2>
BinningThresholds = Lots:20000000,Some:6000000,Little:1000000,None:0
; Format: <Class_1>:<BG_1>|<FG_1>,<Class_2>:<BG_2>|<FG_2>
BinningColors = Lots:#7bccc4|#ffffff,Some:#bae4bc|#000000,Little:#f0f9e8|#000000,None:#ffffff|#000000

[Decoding]
TransitionModelType = static
StaticTransitionMatrixFile = demo_data/dummy_transition_matrix.txt
InitialStateMobilityProb = 0.1

[Lexicalization]
MinimumFrequency = 5
